### ISSUE TITLE
A imagem resultante tem bordas brancas

### ISSUE THREAD

**Issue by LincolnVS** [lincolnvs/blue-bird-words#2]
Como se pode ver na imagem abaixo, a imagem resultante contem bordas brancas mesmo se definir o fundo como 'black'.

![image](https://user-images.githubusercontent.com/18398969/83924655-809f2f80-a75b-11ea-94d5-3aa5fbccfc78.png)

**Comment by lincolnvs** [comment]
Resolvido na versão #b4d2dd92c8c2696628c933a8e8af333eb50485f5

**Comment by LincolnVS** [comment]
Resolvido

![image](https://user-images.githubusercontent.com/18398969/84044875-7f9a1800-a97e-11ea-9bd7-70937c032fba.png)
